#!/usr/bin/env python3
"""Turn a roster and a category list into the SQL that seeds the workshop DB.

    python3 seed.py roster.txt categories.txt "Workshop name" 2026-09-20 > seed.sql
    wrangler d1 execute workshop --remote --file=seed.sql

roster.txt and categories.txt are one entry per line; blank lines and lines
starting with # are ignored. **roster.txt is gitignored** — attendee names are
never committed. The site fetches the roster from the API at runtime instead,
which is also what lets you add walk-ins during the workshop without a rebuild.

Re-running this is safe: every statement is INSERT OR IGNORE, so seeding twice
does not duplicate anyone. Ids are positional, so do not reorder roster.txt
between runs once voting has started.
"""

import sys, os


def lines(path):
    if not os.path.exists(path):
        sys.exit('missing file: %s' % path)
    out = []
    for raw in open(path, encoding='utf-8'):
        s = raw.strip()
        if s and not s.startswith('#'):
            out.append(s)
    return out


def q(s):
    """SQL single-quoted literal."""
    return "'" + s.replace("'", "''") + "'"


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    people = lines(sys.argv[1])
    cats = lines(sys.argv[2])
    name = sys.argv[3] if len(sys.argv) > 3 else 'Workshop'
    date = sys.argv[4] if len(sys.argv) > 4 else ''

    seen = set()
    dupes = [p for p in people if p.lower() in seen or seen.add(p.lower())]
    if dupes:
        # Two identical names would silently become one node in the network.
        sys.exit('duplicate names in roster: %s' % ', '.join(dupes))

    print('-- generated by seed.py; do not edit by hand')
    print('BEGIN TRANSACTION;')
    for i, p in enumerate(people, 1):
        print('INSERT OR IGNORE INTO attendee (id, name) VALUES (%s, %s);'
              % (q('p%02d' % i), q(p)))
    for i, c in enumerate(cats, 1):
        print('INSERT OR IGNORE INTO category (id, label, added_live) VALUES (%s, %s, 0);'
              % (q('c%02d' % i), q(c)))
    print('INSERT OR REPLACE INTO setting (key, value) VALUES (%s, %s);'
          % (q('workshop_name'), q(name)))
    if date:
        print('INSERT OR REPLACE INTO setting (key, value) VALUES (%s, %s);'
              % (q('workshop_date'), q(date)))
    print('COMMIT;')
    print('-- %d attendees, %d predefined categories' % (len(people), len(cats)),
          file=sys.stderr)


if __name__ == '__main__':
    main()
